### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by knightli** [oskros/MF_counter_releases#13]
thank you for releasing such a good application.

Do you have a plan for i18n support?

I can contribute for i18n.
But I'm not familar with python and i18n framework
If the code is refactor for i18n
I believe there will be more people willing to do related work for i18n

Anyway, when you decided direction for i18n, i can contribute.

**Comment by oskros** [comment]
thanks. sorry I do not plan on making i18n support - this app will stay solely in python
