### ISSUE TITLE
Feature: have session timer only accumulate run times

### ISSUE THREAD

**Issue by rgoliveira** [oskros/MF_counter_releases#2]
I AFK a lot while playing, doing runs here and there when I have some free time at night (but leaving the game open), so a lot of my "session" time was not actually spent playing. If I could have this counter be just the sum of all my runs it'd be great.

**Comment by oskros** [comment]
I dont know if it directly solves your issue, but if you go to "Profiles" tab and click "Open Archive Browser", you can see the sum of all your run times

**Comment by oskros** [comment]
Latest version I have changed the session timer to only accumulate while d2 is open, I wonder if this solves the issue for you? I'd prefer not making it the sum of runs

**Comment by rgoliveira** [comment]
That's some progress, yes... Though usually I only close the game when I don't intend to play anymore, so I close the counter too. But I don't have any strong feelings about this issue. Feel free to close it if you won't fix/create an option. I'm more concerned with run times being as automatic and accurate as they can be (see #1).

**Comment by rgoliveira** [comment]
Closing this. I don't think I need it anymore, and you shouldn't put time into this, honestly.
