### ISSUE TITLE
Bug: crash when running for a long time

### ISSUE THREAD

**Issue by rgoliveira** [oskros/MF_counter_releases#4]
I noticed a few similar crashes and stopped to actually read the message. It looks like some variable/property is overflowing if the counter and/or the game is open for too long.

Here's an image of the exception: 
![image](https://user-images.githubusercontent.com/1731173/95544629-0e24b180-09d2-11eb-8cc7-6b110cd7607f.png)

PS: I was not in a run, though the session time was still ticking, as always.
PS2: I'm usually AFK for some time and come back to this, or I left the game & counter in the background for a long time and it just crashes.

**Comment by oskros** [comment]
This is apparently an error occuring in the library I am using for memory reading (pymem) - Will pass it on to that project. Thanks

**Comment by oskros** [comment]
Solved in 1.4.1 I believe
