### ISSUE TITLE
"failed to execute script main"

### ISSUE THREAD

**Issue by jovaye** [oskros/MF_counter_releases#5]
hello,

 my pc crashed while i was using the mf counter and when i logged back in and tried to run the .exe i started receiving a 

Fatal error detected
"Failed to execute script main" error.

it's creating a log file stating

15:26:38,533 root ERROR Expecting ',' delimiter: line 13975 column 27 (char 371371)
Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "main_frame.py", line 112, in __init__
  File "main_frame.py", line 274, in sorted_profiles
  File "main_frame.py", line 272, in sort_key
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13975 column 27 (char 371371)

i'm hoping there's a way to recover the data that was currently being stored? my power went out over the weekend and when i loaded pc back up the run i was in was still there so i'm there's an easy fix to recover?

**Comment by oskros** [comment]
So you solved this yourself?

**Comment by jovaye** [comment]
> So you solved this yourself?

The fatal error detected was resolved by moving the corrupt profile. I viewed the profile text in notepad and it looks like there's data missing from the start and end of the document when compared to a working profile. I assumed with the missing data I couldn't do too much to recover it

**Comment by oskros** [comment]
It's unfortunate, probably the power went out right in the middle of a file save, and that is why the profile data was corrupted.. You are welcome to try and send the file to me, maybe I can recover some data from it

**Comment by jovaye** [comment]
https://drive.google.com/file/d/15IRRjPnN0e37YQTlPsao7WCul15gQ0ZI/view?usp=sharing

That's a google drive of the file, if there's a better way of sending let me know! Not a huge deal either way but I had it running for like  4 days with over 1,000 runs logged so I was a little distraught when it corrupted. Thank you for your assistance!

**Comment by oskros** [comment]
[LK.zip](https://github.com/oskros/MF_run_counter/files/5568954/LK.zip)

You can just upload directly here :) It works now, but all drop data was lost unfortunately, if you added any

**Comment by jovaye** [comment]
Seem to be getting the Failed to execute script trying to put that in the profile folder - is there anything in particular I should be doing to get it to work?

**Comment by oskros** [comment]
I uploaded a wrong version before editing the post, maybe try re-downloading it. Otherwise if you keep getting problems feel free to join the discord for MF run counter (find the link in the About tab), then it is easier to talk!

Also, I hope you unzipped it before putting it back into the profile folder?

**Comment by oskros** [comment]
In either case, your problem helped me realise a problem with the code that allows these things to happen in the rare case of a sudden power down. In the next version I release, it will no longer be possible to get corrupted files in these cases
