### ISSUE TITLE
Diablo 2 Resurrected Support

### ISSUE THREAD

**Issue by cwn-dev** [oskros/MF_counter_releases#8]
Any chance auto mode (memory reader) will support D2R?

**Comment by tomekmak** [comment]
I would love to see D2R version ;-)

**Comment by oskros** [comment]
I would love to see that as well :) feel free to make a pull request - I dont have time for implementing this change anywhere in the near future

**Comment by Nuresto** [comment]
Maybe one day we'll be so lucky for someone knowledgeable enough to make our dreams come true.

**Comment by oskros** [comment]
Resolved for simple automode with the latest release
